// <auto-generated />
namespace EOWebShop.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class InitSetup04122017_alen : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(InitSetup04122017_alen));
        
        string IMigrationMetadata.Id
        {
            get { return "201712041922110_InitSetup04122017_alen"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
